bind 127.0.0.1
port 6379
protected-mode yes
daemonize no
supervised no
loglevel notice
logfile ""

dir "Path/To/Redis-x64-5.0.14.1/data" # Change to the folder with redis
  
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
appendonly no
